version: '3'
services:
  mongodb:
    image: arm64v8/mongo:4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - webbee:/data/db
      - ./init-scripts/init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_DATABASE={DB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME={DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={DB_ROOT_PASSWORD}
    platform: linux/arm64/v8
    expose:
      - 27017
volumes:
  webbee:
