version: '3'
services:
  mongodb:
    image: arm64v8/mongo:4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - webbee_vol_new:/data/db
      - ./init-scripts/init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_DATABASE=your-database-name
      - MONGO_INITDB_ROOT_USERNAME=your-username
      - MONGO_INITDB_ROOT_PASSWORD=your-password
    platform: linux/arm64/v8
    expose:
      - 27017
volumes:
  webbee_vol_new:
